### ISSUE TITLE
Problem when trying to load the 3d map

### ISSUE THREAD

**Issue by silasstec** [RalucaNicola/the-globe-of-extremes#1]
Hello, good afternoon!

I had done one pull in your code and now I'm trying to run the application, but I'm having one problem when I try to run the application.

I'm receiving this error:
![image](https://user-images.githubusercontent.com/77503063/105111822-a9d9b980-5ab9-11eb-9d31-daa33d688c5e.png)

but If I check the document he is in the folder:

![image](https://user-images.githubusercontent.com/77503063/105111863-bf4ee380-5ab9-11eb-813f-a94e4d479f57.png)

Can you please help me with this issue ?

**Comment by arcinarisk** [comment]
I have the same issue, please help.

**Comment by hasanradi93** [comment]
I have the same issue, please help.

**Comment by RalucaNicola** [comment]
sorry, I just saw this. You need a webserver to serve the files, loading them from the file disk won't work. You can use the built-in python server: https://anvileight.com/blog/posts/simple-python-http-server/
